### ISSUE TITLE
Token Claim Name  -  preferred_username

### ISSUE THREAD

**Issue by hermann-san** [cuzy-app/humhub-modules-auth-keycloak#10]
Hi, 
Thanks for creating this module.  I've 2 small comments on the config instructions. 

1. I was a bit confused by the mention of oAuth 2.0 in the module name. I was looking for OpenID keyword (as other Apps are also call it) and I couldn't find it.

2. In Keycloak   ----  Clients - Client details - Dedicated scopes - Mapper details
(modification of "Username")

Token Claim Name is already filled by default with "preferred_username"  . There was no "id",  as mentioned in the instructions. So IMO that point can be removed. 

![image](https://github.com/cuzy-app/humhub-modules-auth-keycloak/assets/7679654/cfd9d298-36eb-411a-a541-6ce1672e3e66)

![image](https://github.com/cuzy-app/humhub-modules-auth-keycloak/assets/7679654/3c2de33e-cf52-453c-b67e-e10772579b66)

Otherwise the basic integration with Keycloak worked for me.

**Comment by marc-farre** [comment]
Thanks for your suggestions.

1. This module uses the oAuth 2 protocol. It's planned to update it to use Open ID, but it's currently not done.

2. Maybe it's because you should use a "User Property" mapper type instead of a "User Attribute"?
This is my configuration:
![image](https://github.com/cuzy-app/humhub-modules-auth-keycloak/assets/23310825/b24a3d4e-af26-4a20-bc32-e76a4937e03d)

What is your Keycloak version?

**Comment by hermann-san** [comment]
Keycloak version is 21.2

1. I did use the OpenID Client, that's why I thought it's OpenID. Thanks for clarification though.
![Auswahl_004](https://github.com/cuzy-app/humhub-modules-auth-keycloak/assets/7679654/e24a03f3-3a1e-4e53-a2d4-2da6568bfdda)

2. The log-in works fine, even with User Attribute. 
But log-out doesn't work. When I click log-out, there is a keycloak error.  (invalid redirect URI)  , This URI in Keycloak is simply https://[server FQDN) which works fine for log-in.  But that a different issue I've not looked into in detail yet.
I don't know if it's related to the mapper type.
Also I can't adjust the mapper type when I select user name with predefined mapper. Mapper type is already filled out  with user attribute and grayed out. I can't change it. 
I could add mapper "by configuration". Then I can change all values, but Humhub Keycloak modul instructions say predefined role IMO. If I really need to , I can change it to User Property

![image](https://github.com/cuzy-app/humhub-modules-auth-keycloak/assets/7679654/b52248ef-13ad-4f4f-bd33-c57451adbd29)

Thanks

**Comment by marc-farre** [comment]
For the logout from Humhub, if you haven't checked "Remove user's Keycloak sessions after logout", this module should have no action on logout.
