### ISSUE TITLE
Error after updating

### ISSUE THREAD

**Issue by jooooaah** [cuzy-app/humhub-modules-auth-keycloak#12]
After updating the most recent version of (1.4.1) keycloak-login the most recent humhub version don't work anymore. After hitting the keycloak authentication button  keycloak mask shows up - i can enter my credentials but the redirect link goes back to the login-page.

Sory that i can't provide more data - it's on humhub professional hosting and with help of humhub support we step down to older plugin version - now it works again.

**Comment by marc-farre** [comment]
What is the version of your Keycloak server?

Can you check the logs in Administration -> Information -> Logging?

**Comment by jooooaah** [comment]
unfortunately, we can no longer track this exactly - it war a update on  a live system.  KC is 17.0.1 but we currently preparing update on 23.0.5

**Comment by marc-farre** [comment]
I see. The new module version was only tested on Keycloak 22 and 23.
Please let me know if it works after upgrading to Keycloak 23 and I will add this requirement in the module documentation.

FYI, this new version of the module uses Open ID connect protocol instead of Oauth 2.

And also it requires PHP 8.2 ([see requirements here](https://github.com/cuzy-app/humhub-modules-auth-keycloak?tab=readme-ov-file#requirements)). You should check the version of your PHP in Administration -> Information -> Prerequisites

**Comment by jooooaah** [comment]
thanks - I will report here if the error occurs again after upgrading to version 23. We have already figured out the PHP version and fixed it :) good hint with OIDC!

**Comment by Fabien-inexine** [comment]
I have the same problem after updating from 1.3 to 1.4.1. My version of keycloak is 23.0.3, php 8.1 and humhub 1.15.3.

**Comment by Fabien-inexine** [comment]
I use the market place version. I switched to php 8.2 but I have the same problem. I’m on ubuntu 22. 

The keycloak configuration is ok. The module configuration also normally.

**Comment by marc-farre** [comment]
@Fabien-inexine Can you have a look to this:

![image](https://github.com/cuzy-app/humhub-modules-auth-keycloak/assets/23310825/3e66c85a-f936-4379-9e5b-b8f5eff3d0ab)

![image](https://github.com/cuzy-app/humhub-modules-auth-keycloak/assets/23310825/a691e8c0-d5bf-46aa-b6f5-656b05028d23)

![image](https://github.com/cuzy-app/humhub-modules-auth-keycloak/assets/23310825/4b61a909-5e34-4fd3-ac2a-334313be4acd)

And also if you have error messages in the Console tab, or in Humhub logging?

**Comment by Fabien-inexine** [comment]
I don’t have a call on authenticate/session_code
Here is the debug when I click on "connect with keycload"

![Capture d’écran du 2024-02-16 11-23-17](https://github.com/cuzy-app/humhub-modules-auth-keycloak/assets/103122659/a57c42d0-c9fa-43cb-b938-35c4598d7c09)

**Comment by marc-farre** [comment]
Sorry, but I don't know what's happening.
If you need paid support, contact me on https://cuzy.app/contact

I will need:
- an admin access to your Keycloak
- or a testing client (I'll send you the settings to add)
- or the settings of your current client (you'll need to temporarily add the URL of my HumHub instance in "Valid redirect URIs")

And a screenshot of your module settings on HumHub.

This will allow me to test on my local HumHub instance and fix the issue.

**Comment by marc-farre** [comment]
@Fabien-inexine thanks very much for your researches and your feedback.

I didn't know it was a requirement, as it's marked as highly recommended in the JWT Key Management Component library: 
https://web-token.spomky-labs.com/introduction/pre-requisite

I've updated the module requirements in the last commit: 
https://github.com/cuzy-app/humhub-modules-auth-keycloak/commit/7a48f151b11512e2e4226ef74c6cc310a86efc78#diff-0b5ca119d2be595aa307d34512d9679e49186307ef94201e4b3dfa079aa89938R26

And I've released a new version of the module: https://github.com/cuzy-app/humhub-modules-auth-keycloak/releases/tag/1.4.2
It should be soon available on the marketplace (it only adds these new requirements).
