### ISSUE TITLE
Changes to Realm Field

### ISSUE THREAD

**Issue by ArchBlood** [cuzy-app/humhub-modules-auth-keycloak#3]
Maybe it would be a good idea to disable the realm field using `'disabled' => true`, this or remove the field and replace it with a dropdown option, your thoughts?

**Comment by funkycram** [comment]
Sorry for replying so late... Is your request still up to date with the last version of the module?
If yes, could you precise which field? Is it on the configuration page `/auth-keycloak/admin`?
Thanks!

**Comment by ArchBlood** [comment]
> Sorry for replying so late... Is your request still up to date with the last version of the module?
> If yes, could you precise which field? Is it on the configuration page `/auth-keycloak/admin`?
> Thanks!

 This field here

```php
<?=​ ​$​form​->​field​(​$​model​, ​'realm'​) ​?>
```

**Comment by funkycram** [comment]
OK, thanks, I see. But why should we disable it? I'm not sure I understand.

This field should even be mandatory (it's now the case) as we need to know the realm name to create the full base URL for Oauth2 communication: https://github.com/cuzy-app/humhub-modules-auth-keycloak/blob/d57de697df5481facf9b30ac0055093129429ec2/authclient/Keycloak.php#L47

It's also used for the API if you've activated this optional feature.

And I cannot do a dropdown field as I cannot know the realm name. On basic Keycloak installation, the realm is "master" (the default value), but you can create as many realm as you want on Keycloak and name them as you which.

**Comment by ArchBlood** [comment]
> OK, thanks, I see. But why should we disable it? I'm not sure I understand.
> 
> This field should even be mandatory (it's now the case) as we need to know the realm name to create the full base URL for Oauth2 communication: https://github.com/cuzy-app/humhub-modules-auth-keycloak/blob/d57de697df5481facf9b30ac0055093129429ec2/authclient/Keycloak.php#L47
> 
> It's also used for the API if you've activated this optional feature.
> 
> And I cannot do a dropdown field as I cannot know the realm name. On basic Keycloak installation, the realm is "master" (the default value), but you can create as many realm as you want on Keycloak and name them as you which.

How about an idea of making this field optional while using a dropdown field that will not only display the default option but anything placed in the realm field?

**Comment by ArchBlood** [comment]
> Sorry, I don't really understand your proposal.
> As we cannot know the realm name, how could we have a dropdown field instead?
> 
> On Keycloak the field is a text input to:
> ![image](https://user-images.githubusercontent.com/23310825/173758123-ce70865c-6b0e-4abd-9d0d-036c909a0c9b.png)
> 
> On Humhub we ask to copy this field value, so the field type should be the same.

I had thought that it would have been a good idea to have a dropdown option in cases where multiple realm names could have been entered and one of the options could have been selected from the dropdown option.

**Comment by funkycram** [comment]
I can't retrieve the list of realms without having access to the API (because the realms list is different for each Keycloak installation) and I need the domain to query the API...
That's why a dropdown field is not possible, but thanks for the idea.
