### ISSUE TITLE
Force Keycloak to HumHub Sync

### ISSUE THREAD

**Issue by MarcoGriep88** [cuzy-app/humhub-modules-auth-keycloak#4]
Hi there, 

i have a keycloak running and my users are registering on keycloak and not on HumHub. Directly after Registering my users dont exist in HumHub. I guess this is because of the Sync Settings in the API. There is an realtime Sync from HumHub into Keycloak. Can i somehow force this process? Keycloak as "Single Source of Truth" for Authorization is necessary because there are other applications (client_ids) that exists for longer.

If i need to adjust this by code, thats fine. 

Best Regards
Marco

**Comment by funkycram** [comment]
Sorry, I'm not sure I understand your problem.
You say " Directly after Registering my users dont exist in HumHub": This isn't normal. You don't need to activate API sync for that.
I don't understand "Single Source of Truth" either: what I do, is create a client on Keycloak specifically for Humhub. That way there are no interactions with others apps.

Perhaps you could add screenshots of you Keycloak settings on Humhub, you client on Keycloak and the Mapper tab of your client.

**Comment by MarcoGriep88** [comment]
Hi funkycram,

no problem, i will try to do my best to explain :)

I having multiple Web Apps that are using Keycloak to authorize their users. Those are working fine right now. Now i wanted to build an community around those webapps with keycloak so that those users can access keycloak with their user accounts. 

Unfortunatly HumHub tells my that the users do not exist. 
![001](https://user-images.githubusercontent.com/34394493/172048155-b89dda63-767a-4230-ac62-c01d95de638a.png)

Even when i click on "sign in with keycloak" this issue happens. The Use can login in Keycloak, gets an JWT Token and gets redirected to HumHub, HumHub says "no user exists". Everything works fine with my administrator account because i used the same account on Keycloak and on Install from HumHub. 

I guess this has something todo with the HumHub<->Keycloak Sync. But this is only a "guess".

Over here my settings:

![002](https://user-images.githubusercontent.com/34394493/172048645-b9e9a1ec-bd43-4543-a090-15e435418918.png)

![003](https://user-images.githubusercontent.com/34394493/172048650-765cde04-89a9-413a-af12-0966dc6e810d.png)

**Comment by funkycram** [comment]
Only the first screenshot could have an impact on your problem. 
But as it works with an existing account (your admin account), it means you might have specific settings on Humhub disabling account creation.
Can you create an account without Keycloak?
Could you check in Administration -> User -> Settings that "New users can register" is ticked?
If it still doesn't work, could you try, in the Keycloak settings (of the Humhub module) to untick "Automatic login"?

**Comment by MarcoGriep88** [comment]
Hello,

I'm currently out of the office, I'll try your suggestions as soon as I have access again.

However, what I can say is: If I create a user in Keycloak, I cannot log in directly to HumHub. After 24 hours the whole thing works without issues. 

I'll try to adjust your comments and give feedback. Thanks in advance for your time.

**Comment by MarcoGriep88** [comment]
Hey there,

thanks alot. The "New users can register" was really the issue. Now it works fine. 
Thanks alot :)
