### ISSUE TITLE
OIDC Logout not working

### ISSUE THREAD

**Issue by gabriel-gfs** [cuzy-app/humhub-modules-auth-keycloak#6]
When I logout from humhub I expect this plugin to log me out from Keycloak as well or at least give me the option of enabling this, as it is a security risk for people not being able to logout on a public PC without going to the logout endpoint themselves.

Maybe its just me that is misconfiguring something, but I cant seem to find a way to logout from Humhub properly.

Kind Regards
Gabriel

**Comment by funkycram** [comment]
You might have ticked the "Automatic login" option without the "Remove user's Keycloak sessions after logout".
In that case, Humhub always tries to login, even after logout, and login is successful if the user is still logged in to Keycloak.
So you should fill the "Keycloak API admin username" and password fields, and tick "Remove user's Keycloak sessions after logout".
